version: 0.2
phases:
  install:
    commands:
      - echo "Installing AWS CLI...and the SNS"
      - pip install awscli
  build:
    commands:
      - echo "Updating S3 index file..."
      - aws s3 cp . s3://awyes-s3-bucket/ --recursive
