version: 0.2
phases:
  install:
    commands:
      - echo "Installing AWS CLI..."
      - pip install awscli
  build:
    commands:
      - echo "Updating S3 index file..."
      - aws s3 cp index.html s3://my-bucket/
